**TLDR: scipy is only reliable and consistent with RDKit for bit vector inputs. For count fingerprint vectors, use `BulkTanimotoSimilarity` or `BulkDiceSimilarity` from RDKit**

In [1]:
import numpy as np
import pandas as pd
from scipy.spatial import distance

from joblib import Parallel, delayed

from rdkit import Chem, DataStructs
from rdkit.Chem import AllChem

In [2]:
df_esol = pd.read_csv('data/ESOL/delaney.csv')
df_esol

,smiles,logSolubility
0,OCC3OC(OCC2OC(OC(C#N)c1ccccc1)C(O)C(O)C2O)C(O)...,-0.770
1,Cc1occc1C(=O)Nc2ccccc2,-3.300
2,CC(C)=CCCC(C)=CC(=O),-2.060
3,c1ccc2c(c1)ccc3c2ccc4c5ccccc5ccc43,-7.870
4,c1ccsc1,-1.330
...,...,...
1123,FC(F)(F)C(Cl)Br,-1.710
1124,CNC(=O)ON=C(SC)C(=O)N(C)C,0.106
1125,CCSCCSP(=S)(OC)OC,-3.091
1126,CCC(C)C,-3.180


In [3]:
df_esol['inchi_key'] = df_esol.smiles.apply(lambda x: Chem.inchi.MolToInchiKey(Chem.MolFromSmiles(x)) if Chem.MolFromSmiles(x) else 'Remove')

In [4]:
df_esol = df_esol.drop_duplicates(subset='inchi_key')
df_esol.shape

(1117, 3)

In [5]:
smiles_list1 = df_esol.smiles.values[:600]
smiles_list2 = df_esol.smiles.values[600:]

# Calculate Tanimoto/Jaccard Similarity with Bit Vectors

These methods agree!

## RDKit

In [6]:
fp_gen = AllChem.GetRDKitFPGenerator(minPath=1, maxPath=2, fpSize=2048)
def get_RDKit_fp(smi: str):
    mol = Chem.MolFromSmiles(smi)
    return fp_gen.GetFingerprint(mol)

In [7]:
def _bulk_tanimoto(fp, fp_list):
    """
    Thin wrapper around DataStructs.BulkTanimotoSimilarity required because
    Boost.Python functions cannot be pickled by joblib's loky backend.
    """
    return DataStructs.BulkTanimotoSimilarity(fp, fp_list)

In [8]:
def get_similarity_matrix(smiles_list1, smiles_list2, ncpus=1):
	"""
	Returns a matrix of Tanimoto similarities as a numpy array
	of size smiles_list1 x smiles_list2.

	Progress is measured by the number of smiles in smiles_list1.
	"""
	# Pre-compute all fingerprints once before parallelising
	fp_list1 = [get_RDKit_fp(smi) for smi in smiles_list1]
	fp_list2 = [get_RDKit_fp(smi) for smi in smiles_list2]

	results = Parallel(n_jobs=ncpus, backend="loky", batch_size="auto", verbose=5)(
        delayed(_bulk_tanimoto)(fp, fp_list2) for fp in fp_list1
    )

	return np.array(results)

In [9]:
similarity_matrix_rdkit = get_similarity_matrix(smiles_list1, smiles_list2, ncpus=2)
similarity_matrix_rdkit.shape

[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done  18 tasks      | elapsed:    0.4s
[Parallel(n_jobs=2)]: Done 600 out of 600 | elapsed:    0.6s finished


(600, 517)

In [10]:
similarity_matrix_rdkit

array([[0.13043478, 0.05263158, 0.28571429, ..., 0.09803922, 0.14285714,
        0.23529412],
       [0.2173913 , 0.15789474, 0.25      , ..., 0.01694915, 0.        ,
        0.13559322],
       [0.        , 0.41176471, 0.        , ..., 0.05263158, 0.33333333,
        0.04444444],
       ...,
       [0.14285714, 0.        , 0.33333333, ..., 0.        , 0.        ,
        0.22857143],
       [0.09090909, 0.        , 0.18518519, ..., 0.01960784, 0.        ,
        0.09259259],
       [0.125     , 0.        , 0.25      , ..., 0.        , 0.        ,
        0.20512821]])

## Scipy

In [11]:
fps1 = [get_RDKit_fp(smi) for smi in smiles_list1]
fps2 = [get_RDKit_fp(smi) for smi in smiles_list2]

In [12]:
# this calculates distance so subtract 1 to make it similarity
similarity_matrix_scipy = 1 - distance.cdist(fps1, fps2, metric='jaccard')
similarity_matrix_scipy.shape

(600, 517)

In [13]:
similarity_matrix_scipy

array([[0.13043478, 0.05263158, 0.28571429, ..., 0.09803922, 0.14285714,
        0.23529412],
       [0.2173913 , 0.15789474, 0.25      , ..., 0.01694915, 0.        ,
        0.13559322],
       [0.        , 0.41176471, 0.        , ..., 0.05263158, 0.33333333,
        0.04444444],
       ...,
       [0.14285714, 0.        , 0.33333333, ..., 0.        , 0.        ,
        0.22857143],
       [0.09090909, 0.        , 0.18518519, ..., 0.01960784, 0.        ,
        0.09259259],
       [0.125     , 0.        , 0.25      , ..., 0.        , 0.        ,
        0.20512821]])

In [14]:
np.isclose(similarity_matrix_rdkit, similarity_matrix_scipy, rtol=1e-8, atol=1e-10).all()

True

# Calculate Tanimoto/Jaccard Similarity with Count Vectors

RDKit and Scipy disagree here since Scipy's jaccard is not identical to Jaccard/Rogers Tanimoto for count vectors.

See: https://github.com/rdkit/rdkit/blob/3f1a4b1d6a8a457279e5b8cceaf2504ffffc149c/rdkit/Chem/ReducedGraphs.py#L18

## RDKit

In [15]:
fp_gen = AllChem.GetRDKitFPGenerator(minPath=1, maxPath=2, fpSize=2048)
def get_RDKit_fp(smi):
	mol = Chem.MolFromSmiles(smi)
	return fp_gen.GetCountFingerprint(mol)

In [16]:
def get_similarity_matrix(smiles_list1, smiles_list2, ncpus=1):
	"""
	Returns a matrix of Tanimoto similarities as a numpy array
	of size smiles_list1 x smiles_list2.

	Progress is measured by the number of smiles in smiles_list1.
	"""
	# Pre-compute all fingerprints once before parallelising
	fp_list1 = [get_RDKit_fp(smi) for smi in smiles_list1]
	fp_list2 = [get_RDKit_fp(smi) for smi in smiles_list2]

	results = Parallel(n_jobs=ncpus, backend="loky", batch_size="auto", verbose=5)(
        delayed(_bulk_tanimoto)(fp, fp_list2) for fp in fp_list1
    )

	return np.array(results)

In [17]:
similarity_matrix_rdkit = get_similarity_matrix(smiles_list1, smiles_list2, ncpus=1)
similarity_matrix_rdkit.shape

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done 161 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done 287 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done 449 tasks      | elapsed:    0.1s


(600, 517)

In [18]:
similarity_matrix_rdkit

array([[0.11504425, 0.01149425, 0.15789474, ..., 0.04433498, 0.09756098,
        0.1797235 ],
       [0.37288136, 0.075     , 0.44444444, ..., 0.01666667, 0.        ,
        0.22058824],
       [0.        , 0.14893617, 0.        , ..., 0.04651163, 0.38095238,
        0.01515152],
       ...,
       [0.24      , 0.        , 0.35294118, ..., 0.        , 0.        ,
        0.39130435],
       [0.20689655, 0.        , 0.30120482, ..., 0.01010101, 0.        ,
        0.21008403],
       [0.2875    , 0.        , 0.359375  , ..., 0.        , 0.        ,
        0.25      ]])

## Scipy

In [19]:
fp_gen = AllChem.GetRDKitFPGenerator(minPath=1, maxPath=2, fpSize=2048)
def get_RDKit_fp(smi):
	mol = Chem.MolFromSmiles(smi)
	return fp_gen.GetCountFingerprintAsNumPy(mol)

In [20]:
fps1 = [get_RDKit_fp(smi) for smi in smiles_list1]
fps2 = [get_RDKit_fp(smi) for smi in smiles_list2]

In [21]:
similarity_matrix_scipy = 1 - distance.cdist(fps1, fps2, metric='jaccard')
similarity_matrix_scipy.shape

(600, 517)

In [22]:
similarity_matrix_scipy

array([[0.        , 0.        , 0.14285714, ..., 0.01960784, 0.        ,
        0.19607843],
       [0.        , 0.15789474, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.23529412, 0.        , ..., 0.        , 0.16666667,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.11428571],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.07407407],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

These results are not even close. Double check scipy's formula!

Scipy's jaccard metric internally binarizes its inputs before computing so it treats any nonzero value as 1. This means it's computing binary Jaccard on the support of the count vector.

In [23]:
np.isclose(similarity_matrix_rdkit, similarity_matrix_scipy, rtol=1e-8, atol=1e-10).all()

False

# Calculate Dice Similarity with Bit Vectors
RDKit and Scipy agree here!

## RDKit

In [24]:
fp_gen = AllChem.GetRDKitFPGenerator(minPath=1, maxPath=2, fpSize=2048)
def get_RDKit_fp_bit(smi):
	"""Generate a bit vector fingerprint for Dice similarity."""
	mol = Chem.MolFromSmiles(smi)
	return fp_gen.GetFingerprint(mol)

In [25]:
def _bulk_dice(fp, fp_list):
    """
    Thin wrapper around DataStructs.BulkDiceSimilarity required because
    Boost.Python functions cannot be pickled by joblib's loky backend.
    """
    return DataStructs.BulkDiceSimilarity(fp, fp_list)

In [26]:
def get_dice_similarity_matrix(smiles_list1, smiles_list2, ncpus=1):
    """
    Returns a matrix of Dice similarities as a numpy array
    of shape (len(smiles_list1), len(smiles_list2)).
    """
    fp_list1 = [get_RDKit_fp_bit(smi) for smi in smiles_list1]
    fp_list2 = [get_RDKit_fp_bit(smi) for smi in smiles_list2]

    results = Parallel(n_jobs=ncpus, backend="loky", batch_size="auto", verbose=5)(
        delayed(_bulk_dice)(fp, fp_list2) for fp in fp_list1
    )
    return np.array(results)

In [27]:
similarity_matrix_dice_rdkit = get_dice_similarity_matrix(smiles_list1, smiles_list2, ncpus=1)
similarity_matrix_dice_rdkit.shape

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done 161 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done 287 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done 449 tasks      | elapsed:    0.0s


(600, 517)

In [28]:
similarity_matrix_dice_rdkit

array([[0.23076923, 0.1       , 0.44444444, ..., 0.17857143, 0.25      ,
        0.38095238],
       [0.35714286, 0.27272727, 0.4       , ..., 0.03333333, 0.        ,
        0.23880597],
       [0.        , 0.58333333, 0.        , ..., 0.1       , 0.5       ,
        0.08510638],
       ...,
       [0.25      , 0.        , 0.5       , ..., 0.        , 0.        ,
        0.37209302],
       [0.16666667, 0.        , 0.3125    , ..., 0.03846154, 0.        ,
        0.16949153],
       [0.22222222, 0.        , 0.4       , ..., 0.        , 0.        ,
        0.34042553]])

## Scipy

In [29]:
fps1 = [get_RDKit_fp_bit(smi) for smi in smiles_list1]
fps2 = [get_RDKit_fp_bit(smi) for smi in smiles_list2]

In [30]:
similarity_matrix_dice_scipy = 1 - distance.cdist(fps1, fps2, metric='dice')
similarity_matrix_dice_scipy.shape

(600, 517)

In [31]:
similarity_matrix_dice_scipy

array([[0.23076923, 0.1       , 0.44444444, ..., 0.17857143, 0.25      ,
        0.38095238],
       [0.35714286, 0.27272727, 0.4       , ..., 0.03333333, 0.        ,
        0.23880597],
       [0.        , 0.58333333, 0.        , ..., 0.1       , 0.5       ,
        0.08510638],
       ...,
       [0.25      , 0.        , 0.5       , ..., 0.        , 0.        ,
        0.37209302],
       [0.16666667, 0.        , 0.3125    , ..., 0.03846154, 0.        ,
        0.16949153],
       [0.22222222, 0.        , 0.4       , ..., 0.        , 0.        ,
        0.34042553]])

In [32]:
np.isclose(similarity_matrix_dice_rdkit, similarity_matrix_dice_scipy, rtol=1e-8, atol=1e-10).all()

True

# Calculate Dice Similarity with Count Vectors
RDKit and Scipy disagree! 

In [33]:
fp_gen = AllChem.GetRDKitFPGenerator(minPath=1, maxPath=2, fpSize=2048)
def get_RDKit_fp(smi):
	mol = Chem.MolFromSmiles(smi)
	return fp_gen.GetCountFingerprint(mol)

In [34]:
def get_dice_similarity_matrix(smiles_list1, smiles_list2, ncpus=1):
    """
    Returns a matrix of Dice similarities as a numpy array
    of shape (len(smiles_list1), len(smiles_list2)).
    """
    fp_list1 = [get_RDKit_fp(smi) for smi in smiles_list1]
    fp_list2 = [get_RDKit_fp(smi) for smi in smiles_list2]

    results = Parallel(n_jobs=ncpus, backend="loky", batch_size="auto", verbose=5)(
        delayed(_bulk_dice)(fp, fp_list2) for fp in fp_list1
    )
    return np.array(results)

In [35]:
similarity_matrix_dice_rdkit = get_dice_similarity_matrix(smiles_list1, smiles_list2, ncpus=1)
similarity_matrix_dice_rdkit.shape

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done 161 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done 287 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done 449 tasks      | elapsed:    0.1s


(600, 517)

In [36]:
similarity_matrix_dice_rdkit

array([[0.20634921, 0.02272727, 0.27272727, ..., 0.08490566, 0.17777778,
        0.3046875 ],
       [0.54320988, 0.13953488, 0.61538462, ..., 0.03278689, 0.        ,
        0.36144578],
       [0.        , 0.25925926, 0.        , ..., 0.08888889, 0.55172414,
        0.02985075],
       ...,
       [0.38709677, 0.        , 0.52173913, ..., 0.        , 0.        ,
        0.5625    ],
       [0.34285714, 0.        , 0.46296296, ..., 0.02      , 0.        ,
        0.34722222],
       [0.44660194, 0.        , 0.52873563, ..., 0.        , 0.        ,
        0.4       ]])

## Scipy

In [37]:
fp_gen = AllChem.GetRDKitFPGenerator(minPath=1, maxPath=2, fpSize=2048)
def get_RDKit_fp(smi):
	mol = Chem.MolFromSmiles(smi)
	return fp_gen.GetCountFingerprintAsNumPy(mol)

In [38]:
fps1 = [get_RDKit_fp(smi) for smi in smiles_list1]
fps2 = [get_RDKit_fp(smi) for smi in smiles_list2]

In [39]:
similarity_matrix_scipy = 1 - distance.cdist(fps1, fps2, metric='dice')
similarity_matrix_scipy.shape

(600, 517)

In [40]:
similarity_matrix_scipy

array([[2.52380952, 0.25      , 2.81818182, ..., 0.99056604, 1.68888889,
        2.0390625 ],
       [5.55555556, 0.13953488, 6.73846154, ..., 0.09836066, 0.        ,
        2.65060241],
       [0.        , 0.88888889, 0.        , ..., 0.62222222, 3.03448276,
        0.05970149],
       ...,
       [4.64516129, 0.        , 6.52173913, ..., 0.        , 0.        ,
        3.1875    ],
       [4.11428571, 0.        , 5.59259259, ..., 0.04      , 0.        ,
        2.02777778],
       [5.59223301, 0.        , 6.89655172, ..., 0.        , 0.        ,
        5.6       ]])

In [41]:
similarity_matrix_scipy.max()

36.67605633802817

The scipy dice metric is defined for binary vectors only. When you pass integer count arrays, scipy's formula computes `2 * dot(u, v) / (dot(u, u) + dot(v, v))` treating the raw integer values arithmetically, which produces values well above 1 

In [42]:
np.isclose(similarity_matrix_rdkit, similarity_matrix_scipy, rtol=1e-8, atol=1e-10).all()

False